### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by thesam1545** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#1]
I get this error when running script from main.py
![image](https://user-images.githubusercontent.com/90088866/137646924-3d8d6292-8db6-4c39-ac30-712dfba8ddd5.png)

I am on Windows 10 running Python through Visual Studio Code. 
I configured auth.yml file and config.yml file, all correctly.
I also installed all requirements.
I am not a programmer, so excuse me if this is a newbie error. :D

**Comment by armonai** [comment]
Thanks done and ran the script again and started gotting some output which I believe is working now. please confirm that's what is expected.

python3 main.py
working...
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
Checking for coin announcements every 1 minute (in a separate thread)
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
Checking for coin announcements every 1 minute (in a separate thread)
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating. You can comment me out, I live on line 176 in main.py
