### ISSUE TITLE
Multiple trades active

### ISSUE THREAD

**Issue by Azoq** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#105]
Hi
I'm new here - but I just saw this was not mentioned.

So a few days ago the bot started to include Kucoin and an interesting thing happend here. Today it bought LINA first - held this one for about an hour. When KLAY gets released. Everything regarding LINA is forgotten and not sold. Moving on the bot later fails on the KLAY trade as well. (I can post the error log later today - my VPS is currently under maintenance)

I think the solution here could simply be to (1) add a list with the coins currently owned, and (2) loop through this list with the sell logic to have continuos price check all coins 'currently owned'

**Comment by Azoq** [comment]
Add; for some reason the error is not shown in the logs. It just says new coin detected and forgets about the old one. 
![image](https://user-images.githubusercontent.com/20394075/145034307-2048c00d-2a00-4845-8cd2-1a85a0abafa2.png)

**Comment by nitad54448** [comment]
In may case, both coins were purchased
