### ISSUE TITLE
The bot is not buying!

### ISSUE THREAD

**Issue by mayankbisht9** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#110]
the bot is not buying the coins, 
It pops up this error, can you guys help me?

2021-12-08 16:26:15,069 ERROR: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 08 Dec 2021 10:03:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: {"label":"REQUEST_EXPIRED","message":"gap between request Timestamp and server time exceeds 60"}

2021-12-08 16:26:15,069 ERROR: (401)
Reason: Unauthorized

**Comment by nitad54448** [comment]
The error is very explicit : more than 60 seconds between the time of your computer and the server. Check the time (or better, synchronize it with a time-server ) of your computer
