### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'src/config.yml'

### ISSUE THREAD

**Issue by alexjchu** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#132]
The config file was renamed to config.ym, but I still get this error. What's the fix for this?

**Comment by Linus045** [comment]
Due to 2340b957410 the config file needs to be moved into the `src/` directory.
Same location as the current `config.example.yml` file.
Also make sure its named `config.yml`.

**Comment by alexjchu** [comment]
The config.yml is already in the src/ directory. I see that main.py is in the same directory, as well. It's still saying the same when I run main.py: FileNotFoundError: [Errno 2] No such file or directory: 'src/config.yml'

Shouldn't main.py be outside of the src/ directory to fix the error?

**Comment by Linus045** [comment]
Currently the bot is expected to be run from the root directory like so:
`python ./src/main.py`
Which will set the working directory correctly.

**Comment by alexjchu** [comment]
I was meaning to update my earlier post. So, what I did was remove 'src/' from the 5 files mentioned in 2340b95 due to main.py being in the same folder. It's working now. I'm using Windows 10 if that matters. Thank you for your help.

**Comment by Linus045** [comment]
that would also fix the problem yes.
I will close this issue then
