### ISSUE TITLE
Bot did not act on binance listing of ACH and IMX

### ISSUE THREAD

**Issue by Beard81** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#138]
Hey,

Had the bot running lastnight checking both binance and kucoin.  Binance announced that ACH and IMX would be listed, but the bot did not pick up on that listing nor initiate a buy from Gate.io.  I've got it all set up correctly i believe, did anybody else have this issue lastnight?

Thanks

**Comment by Linus045** [comment]
Currently the bot ignores mutli-coin releases.

There is also Issue #91 which talks about the same issue and I would like to keep the discussion to one issue.
Therefore i'm going to close this issue.
Please move over to that issue for further discussions.

You can also check out the discord as there has been some discussion on how to best deal with this case.
