### ISSUE TITLE
430 forbidden response, and 429 response which switching to the main domain.

### ISSUE THREAD

**Issue by matt1966** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#146]
BinanceZH is now returning a 403 response.

Example: https://www.binancezh.com/gateway-api/v1/public/cms/article/list/query?type=1&pageNo=1&pageSize=6

To tackle this, I switched to: https://www.binance.com/gateway-api/v1/public/cms/article/list/query?type=1&pageNo=1&pageSize=6

Which quickly returns a 429 (too many requests) response after a few hits, despite using proxies, user agent rotator, etc.

Does anybody know how to tackle this?

**Comment by Linus045** [comment]
This is a duplicate, see issue #137.
There is currently no way to fix this, other than trying to reduce the request interval.
