### ISSUE TITLE
Error In SSH Server

### ISSUE THREAD

**Issue by thealidev** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#160]
````
# python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from gateio_new_coins_announcements_bot.main import main
ModuleNotFoundError: No module named 'gateio_new_coins_announcements_bot'
````

**Comment by lautaroperrotti** [comment]
Same here.

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from gateio_new_coins_announcements_bot.main import main
ModuleNotFoundError: No module named 'gateio_new_coins_announcements_bot'

**Comment by thealidev** [comment]
I found a solution here for it as i am a good dev  
# To Fix It Active venv In Directory Again :  
```
Linux:
source env/bin/activate

Windows:
env\Scripts\activate.bat
```  
# Then ReInstall Deplumates :
 ```
python3 -m pip install -r requirements.txt
```
# Then Run :
```
python3 main.py
```

**Comment by lautaroperrotti** [comment]
Thank you very much! It worked!

**Comment by thealidev** [comment]
> Thank you very much! It worked!

No Need For Thanks ..
Its My Duty ..
