### ISSUE TITLE
ModuleNotFoundError when running main.py

### ISSUE THREAD

**Issue by federiconoceti** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#162]
ModuleNotFoundError: No module named 'gateio_new_coins_announcements_bot' when running main.py

**Comment by Linus045** [comment]
Please follow steps 1 to 3 from the README.md.
You didn't install the requirements correctly or didn't activate the virtual environment (if you're using one).

To start the bot use
`python main.py`
