### ISSUE TITLE
coin_sl  and frequency never used

### ISSUE THREAD

**Issue by e4rthdog** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#21]
When the scripts load the order from the file and assigns all the variables, `coin_sl `is never used. Instead it uses the `sl `variable from config. is this correct?

Also `frequency `is never used.

**Comment by Linus045** [comment]
Is this still a problem or can this issue be closed?

**Comment by mediax24** [comment]
> Is this still a problem or can this issue be closed?

Can be closed

Cheers
