### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by jaazza** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#22]
I've been working to get this running, but I keep encountering the same error regardless of adjustments made. When executing python3 main.py it gives the following result: 

`File "<fstring>", line 1
    (last_price=)
               ^
SyntaxError: invalid syntax
`

Python has been updated to 3.9.5, and the requirements have been installed. Any advice or solution? Thank you.

**Comment by dovydasrudys** [comment]
Remove = that goes after last_price

**Comment by k-304** [comment]
Ensure you have install pip3.8 like here: https://stackoverflow.com/a/61717037
then run `pip3.8 install -r requirements.txt`

**Comment by Linus045** [comment]
fstrings support = behind the variable name (`f"{SomeVar=}"`) since Python 3.8 (for more info see [here](https://stackoverflow.com/questions/59661904/what-does-equal-do-in-f-strings-inside-the-expression-curly-brackets)).
To fix this issue update your python version to 3.8 or higher
