### ISSUE TITLE
Possible solution for delay 5 minutes 

### ISSUE THREAD

**Issue by VuzzyM** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#50]
Hello

https://dev.binance.vision/t/delay-binance/6996/2 I created a discussion on the binance developers forum and I received such a response for delay 5 minutes

![Screenshot_2021-11-02-18-43-08-699_com android chrome](https://user-images.githubusercontent.com/66425682/139909638-92a8d91f-6dd4-496f-839e-b9555bdcb36b.jpg)

**Comment by nitad54448** [comment]
that means the token is listed and traded on binance. the ideea of the announcements "Binance will list..." was to learn about a listing before this occurs. Otherwise, the announcement should say "Binance listed ...."
