### ISSUE TITLE
MOVR announcement analysis

### ISSUE THREAD

**Issue by marijnl** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#60]
Just for reference:

My bot picked up MOVR at 2021-8-11 2.59.45

This is consistent with the timestamp on binance.com:
![image](https://user-images.githubusercontent.com/3338707/140724619-7d4196ed-d879-4315-ad32-cfa8b3291ee3.png)

In terms of trading activity the wave had already started.

![image](https://user-images.githubusercontent.com/3338707/140725356-61978489-fd00-4143-992d-f5b9457fe827.png)

**Comment by aterjung** [comment]
Here you find an Screenshot made of the 10s Candels from gate.io API. Looks like the Pump started at ~ 02:59:10

<img width="1435" alt="Bildschirmfoto 2021-11-08 um 08 00 11" src="https://user-images.githubusercontent.com/3084302/140735850-133c148b-2426-4f2a-8a0e-c4ce2b6c9843.png">

My Bot catched the announcement at 02:59:25

**Comment by Linus045** [comment]
What's this issue for?
