### ISSUE TITLE
What have I done... 401 error

### ISSUE THREAD

**Issue by Scout-lander** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#65]
Been testing and running fine now this must of done something  I guess please help did I miss something  on resetting it up

2021-11-10 01:26:07,408 ERROR: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 09 Nov 2021 12:26:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: {"label":"INVALID_KEY","message":"Invalid key provided"}

**Comment by Jrjy3** [comment]
Make sure you're using APIv4 keys from gate.io, not APIv2.
